# Метод Гаусса с выбором главного элемента по строке

In [87]:
import numpy as np
import math
import matplotlib.pyplot as plt

$ Ax = b $

In [88]:
def matrix_prod(A, B):
    
    assert A.shape[1] == B.shape[0]
    size = A.shape[1]
    ans = np.zeros((A.shape[0], B.shape[1]))
    for k in np.arange(B.shape[1]):
        for i in np.arange(A.shape[0]):
            cur_value = 0
            for j in np.arange(size):
                cur_value += A[i][j] * B[j][k]
            ans[i][k] = cur_value
    return ans
    
    

In [246]:
def max_in_str(A, i):
    ans = i
    max_value = A[i][i]
    for j in np.arange(i + 1, len(A)):
        if max_value < np.abs(A[i][j]):
            max_value = np.abs(A[i][j])
            ans = j
    return ans
        

In [262]:
def substitution(L, b):
    x = np.zeros(b.shape[0])
    x[0] = b[0]
    for i in np.arange(len(b) - 1):
        x[i + 1] = b[i + 1] - matrix_prod(x[:i + 1], L[i + 1][:i + 1])
    return x

In [258]:
def LU_decomposition(A):
    lu_matrix = np.matrix(np.zeros([A.shape[0], A.shape[1]]))
    n = A.shape[0]

    for k in np.arange(n):
        for j in np.arange(k, n):
            lu_matrix[k, j] = A[k, j] - lu_matrix[k, :k] * lu_matrix[:k, j]
        for i in np.arange(k + 1, n):
            lu_matrix[i, k] = (A[i, k] - lu_matrix[i, : k] * lu_matrix[: k, k]) / lu_matrix[k, k]
    
    L = lu_matrix.copy()
    for i in np.arange(L.shape[0]):
            L[i, i] = 1
            L[i, i+1:] = 0
            
    U = lu_matrix.copy()
    for i in np.arange(1, U.shape[0]):
        U[i, :i] = 0
    P = np.eye(n)
    for k in np.arange(n - 1):
        j_max = max_in_str(U, k)
        P.T[[k, j_max]] = P.T[[j_max, k]]
    
    return (P, L, U)

In [259]:
def solver_gaussian(A, b):
    
    assert A.shape[0] == b.shape[0]
    
    # LU-decomposition 
    P, L, U = LU_decomposition(A)
    x = substitution(L, b)
    
    return L, U, P, matrix_prod(x, P.T)

In [260]:
n = 5
A = np.random.rand(n, n)
b = np.random.rand(n)

In [261]:
# Применим метод Гаусса с выбором главного элемента по строке
L, U, P, x = solver_gaussian(A, b)
print(np.linalg.norm(x - np.linalg.solve(A, b)))

[[ 0.72707839  0.66776831  0.45524332  0.64474703  0.30534209]
 [ 0.         -0.19841726  0.49485454  0.153619    0.56104232]
 [ 0.          0.          0.17694523 -0.4780363   0.57251781]
 [ 0.          0.          0.          2.36654236 -1.76871358]
 [ 0.          0.          0.          0.         -0.05482668]]


IndexError: index 1 is out of bounds for axis 0 with size 1

***To be done...***

***Понять простить***